.circleci/config.yml
CHANGELOG.md
Makefile
ci/github_release.sh

- CircleCI definition with
- build, docker build for all pipelines
- docker hub release and github release for semver tags
- unified changelog version headers so that git tags, docker tags and changelog records do match
- dropped obsolete targets from Makefile

initial CircleCI kickoff, unify CHANGELOG version headers

---

CHANGELOG.md
cmd/slo_exporter.go

* Currently we are unable to easily identify version of the tool
* Contribution guide suggests, slo-exporter should have `--version` command-line flag to be reported back in case of bugs.
* This PR adds `--version` command-line flag to help user to identify what version they actually use.

feat: slo-exporter --version command-line flag

---

CHANGELOG.md
cmd/slo_exporter.go
pkg/pipeline/manager.go
pkg/pipeline/manager_test.go

Resolves #26 
Let Pipeline manager to throw an error when empty pipeline is getting started.
Normal error propagation used although panic could be an option as well.

empty config should be invalid

---

CHANGELOG.md
pkg/prometheus_ingester/query_executor.go

Prometheus-ingester now always expose query_fails_total metric, even when eq 0. This simplifies use of this metric in promql computation - e.g. calculation SLO violation ratio for prometheus-ingester queries, as shown in [all-in-one example](https://github.com/seznam/slo-exporter/blob/master/prometheus/recording_rules/events-over-time-slo-exporter.yaml).

fix: prometheus-ingester query_fails_total metric

---

CHANGELOG.md
cmd/slo_exporter.go
docs/modules/envoy_access_log_server.md
go.mod
go.sum
pkg/envoy_access_log_server/access_log_server.go
pkg/envoy_access_log_server/service_v3.go
pkg/envoy_access_log_server/service_v3_test.go
pkg/envoy_access_log_server/util.go
pkg/pipeline/module.go
pkg/prometheus_exporter/prometheus_exporter_test.go
pkg/stringmap/stringmap.go

~~Both currently supported APIs are covered, [v2](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api), [v3](https://www.envoyproxy.io/docs/envoy/latest/api-v3/api). (Suggestions on how to avoid this awful code duplicity are welcomed :) )~~ Just support for the current stable version (v3) has been added.
What remains to be done within this PR:
~~- [ ] consider adding raw protobuf JSON serialization to the generated event's metadata~~
All-in-one example demonstrating usage will be added within a separate PR.

New ingester module: Envoy access-log-server

---

examples/envoy_proxy/README.md
examples/envoy_proxy/docker-compose.yaml
examples/envoy_proxy/envoy/envoy.yaml
examples/envoy_proxy/slo-exporter/slo_exporter.yaml
examples/envoy_proxy/slo-exporter/slo_rules.yaml

This is built on top of https://github.com/seznam/slo-exporter/pull/37.
While I originally intended to add a separate all_in_one example (or add envoy to the existing all_in_one example), I eventually decided to create just a simple example with just envoy, slo-exporter and traffic generator. This is enough to demonstrate how the new module can be used and configured.
All-in-one example serves rather different purpose - demonstrate the whole SLO computation and visualization, event source does not matter much there, so I'm leaving it with the tailer module for now.

doc: added envoy_proxy example

---

.goreleaser.yml

fix: goreleaser after dropped support for darwin/386 arch

---

CHANGELOG.md
docs/modules/slo_event_producer.md
go.mod
pkg/slo_event_producer/config.go
pkg/slo_event_producer/config_test.go
pkg/slo_event_producer/event_evaluator_test.go
pkg/slo_event_producer/rule.go
pkg/slo_event_producer/rule_test.go
test/Test_MetricsInitialization/slo_rules.yaml

To be more flexible, allow regexp matching of the SLO value in the slo-event-producer rules config

feat slo-event-producer: change slo_matcher from string to regexp matcher

---

CHANGELOG.md
Dockerfile

https://github.com/seznam/slo-exporter/issues/44
This change install ca-certificates to docker base image to fix the issue when prometheusIngester module queries prometheus installation that uses HTTPS

Install ca-certificates to docker base image

---

pkg/tailer/tailer_test.go

`offsetPersistenceTestRun` is quite flaky in the CI pipeline (opposed to when it is run locally). I assume this is a problem related to somewhat shared environment in which CI jobs are run, let's hope that the timeout increase should be enough to mitigate this.

fix: offsetPersistenceTestRun CI job flakiness

---

prometheus/alerts/error-budget.yaml
prometheus/alerts/missing_all_data.yaml
prometheus/alerts/missing_data.yaml
prometheus/alerts/slo_burn_rate.yaml
prometheus/alerts/slo_data_corrections.yaml
prometheus/recording_rules/burn-rate.yaml
prometheus/recording_rules/error-budget.yaml
prometheus/recording_rules/events-over-time.yaml
prometheus/recording_rules/metadata.yaml

- add escalate label to SLO alerts
- improve `slo:violation_ratio` in order to produce result in case there are no errors in given `slo_time_range`
- split `slo:events_over_time` computation into more groups

feat: sync recording rules and alerts

---

Makefile

Previously there was used `go get ...` which updated `go.mod` file.
Now `go install ....@TAG` install module, which states by doc:
>  This is useful for installing executables without affecting the dependencies of the main module.

fix: do not update go.mod by running `make lint`

---

CHANGELOG.md
pkg/relabel/relabel.go
pkg/relabel/relabel_test.go

Configuration of relabel module wasn't checked against proper structure. This MR replaces `yaml.Unmarshal` with `yaml.UnmarshalStrict`

fix: use strict unmarshal in relabel module

---

docs/configuration.md

@david-vavra 
I noticed we forgot to link the module from the modules docs.

docs: add missing mention of the envoyAccessLogServer module

---

CHANGELOG.md
pkg/stringmap/stringmap.go
pkg/stringmap/stringmap_test.go

Previously:
- `StringMap.Merge(nil, x)` would return the `x`, not a new map
- `StringMap.Without(x, nil)` would return the `x`, not the new map -- when x itself was not nil.
Improve the tests to catch this.
While at it, clarify and fix some of the docstrings.
`make e2e-tests` passes.

fix: Make StringMap.Merge, StringMap.Without always return a new map, as documented.

---

CHANGELOG.md
README.md
cmd/slo_exporter.go
docs/modules/prometheus_exporter.md
go.mod
go.sum
pkg/event/slo.go
pkg/prometheus_exporter/aggregating_counter.go
pkg/prometheus_exporter/aggregating_counter_test.go
pkg/prometheus_exporter/exemplars.go
pkg/prometheus_exporter/prometheus_exporter.go
pkg/slo_event_producer/event_evaluator_test.go
pkg/slo_event_producer/rule.go
pkg/slo_event_producer/rule_test.go

@sklik-devops 
This adds support for exposing exemplars using the OpenMetrics format for Prometheus.
This should allow user to link together metrics and tracing or logging. 
For more info, see for example [this blog post](https://vbehar.medium.com/using-prometheus-exemplars-to-jump-from-metrics-to-traces-in-grafana-249e721d4192)
To achieve this, I had to add to the SLO event also the original event it was created from. This will be handy in many other cases later, I think. 
Tested it out and looks working just fine
example of exposed metrics:
```
slo_domain:slo_events_total{result="fail",slo_domain="test-domain"} 1.0 # {traceId="yyyyyyyyy"} 1.0 1.6294153319073987e+09
slo_domain:slo_events_total{result="success",slo_domain="test-domain"} 2.0 # {traceId="zzzzzzzzz"} 1.0 1.6294153319075e+09 …
```

Add exemplars support to the prometheus_exporter module

---

examples/all_in_one/README.md
examples/all_in_one/docker-compose.yaml
examples/all_in_one/grafana/provisioning/dashboards/SLO_Effective_Burn-rate.json
examples/all_in_one/grafana/provisioning/dashboards/SLO_detailed.json
examples/all_in_one/grafana/provisioning/dashboards/SLO_drilldown.json

Syncing Grafana dashboards
Notably, drilldown dashboard has been reworked in order to be more user-friendly.
It now displays total count of success/fail events and 4w error budget on chosen timerange within tables on the right side. The main graph now does display slo-time-range based burn-rate instead of slo-time-range error budget (which is what confused the most users).

feat: sync Grafana dashboards

---

tools/slo-rules-generator/slo-rules-generator.go

Previously:
- the files were being created with the executable bits set
- when writing to an existing file, the file was not truncted, which
lead to leftover data at the end of the file
- errors during file creation & writing were either ignored or
swallowed

fix: Fix file creation and error handling in slo-rules-generator.

---

CHANGELOG.md
prometheus/recording_rules/events-over-time-slo-exporter.yaml

There is currently an error in slo-exporter's slo compuation for uptime slo_class.
We've already decided with @FUSAKLA to move out from this approach and rather include jsonnet mixins to generate alerts based on which ingester module is used. But as it may take some time until we will publish this, this fix should be merged.

fix: slo-exporter's SLO recording rule for uptime success events

---

CHANGELOG.md
pkg/prometheus_ingester/prometheus_ingester.go
pkg/prometheus_ingester/prometheus_ingester_test.go

original implementation counted with viper using yaml library and UnmarshalYAML interface. It was naive, viper uses
mapstructure instead of yaml package

fix: prometheusIngester headers from env

---

CHANGELOG.md
cmd/slo_exporter.go
pkg/prometheus_ingester/prometheus_ingester.go

Since prometheusIgester has support for sending headers, we should send by default user-agent header

feat: prometheusIngester sends user-agent header

---

CHANGELOG.md
docs/modules/prometheus_ingester.md
examples/prometheus/slo_exporter.yaml
pkg/prometheus_ingester/prometheus_ingester.go
pkg/prometheus_ingester/prometheus_ingester_test.go
pkg/prometheus_ingester/query_executor.go

We experienced issues when querying data coming from remote write API, especially for `histogram_increase` query types.
This should allow the user to add a safety buffer to ensure the histogram and data consistency.
In addition to it, there were some minor changes needed to allow testability of the feature and fixed some related mutex copying

feat prometheusIngester: add offset setting for query

---

.circleci/config.yml
CHANGELOG.md

This PR addresses a build issue caused by an unsupported Docker version on CircleCI. The build failure can be viewed ([here](https://app.circleci.com/pipelines/github/seznam/slo-exporter/376/workflows/affe1c77-d687-4743-bed5-3b31c3cd3604/jobs/1574))
```
Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running
```
Remove the remote docker version to use the circleci default.
> According to CircleCI's [building Docker images documentation](https://circleci.com/docs/building-docker-images/#docker-version) and their [remote Docker image support policy](https://circleci.com/docs/remote-docker-images-support-policy/#tagging), the next supported Docker version is `20.10.24`. However, …

fix(ci): remove remote_docker version

---

.goreleaser.yml
CHANGELOG.md

This PR is to fix the issue in releasing multi-platform docker images. 
See issue: https://app.circleci.com/pipelines/github/seznam/slo-exporter/384/workflows/932fb8ac-8631-4d2d-a48b-9dbc083055d2/jobs/1603?invite=true#step-103-96 
```
#6 ERROR: process "/bin/sh -c apt-get update && apt-get install ca-certificates -y && apt-get clean" did not complete successfully: exit code: 1
------
> [2/5] RUN apt-get update && apt-get install ca-certificates -y && apt-get clean:
0.237 exec /bin/sh: exec format error
------
Dockerfile:3
--------------------
1 |     FROM debian:stable-slim
2 |     
3 | >>> RUN apt-get update && apt-get install ca-certificates -y && apt-get clean
4 |     
5 |     COPY slo_exporter  /slo_exporter/
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get …
```

add qemu before release
